name: E2E Tests

on:
  push:
    branches:
      - main
      - develop
      - ai
  pull_request:
    branches:
      - main
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: yarn test:e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const resultsPath = 'test-results/results.json';

            if (fs.existsSync(resultsPath)) {
              const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
              const passed = results.suites.reduce((acc, s) => acc + s.specs.filter(spec => spec.ok).length, 0);
              const failed = results.suites.reduce((acc, s) => acc + s.specs.filter(spec => !spec.ok).length, 0);
              const total = passed + failed;

              const comment = `## E2E Test Results\n\n` +
                `- ✅ Passed: ${passed}\n` +
                `- ❌ Failed: ${failed}\n` +
                `- 📊 Total: ${total}\n` +
                `- ⏱️ Duration: ${results.stats.duration}ms\n\n` +
                (failed > 0 ? `⚠️ Some tests failed. Check the [test report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.` : '✅ All tests passed!');

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
